apiVersion: v1
kind: Pod
metadata:
  name: jigu-pod
spec:
  containers:
    - name: app-db
      image: mysql:latest
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_USER
          value: "jigu"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "db_test"
    - name: jigu-server
      image: jigu-server:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8000