apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-deploy
  ports:
  - nodePort: 31000
    port: 3306
    targetPort: 3306
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-pod # 커플링
  template:
    metadata:
      labels:
        app: mysql-pod # 커플링
    spec: # 파드의 매니페스트와 동일
      containers:
        - name: app-db
          image: mysql:latest
          ports:
            - containerPort: 3306
              name:
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_USER
              value: "jigu"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "db_test"

