apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: web
      port: {{ .Values.service.port.web }}
      targetPort: {{ .Values.service.port.web }}
    - name: db
      port: {{ .Values.service.port.db }}
      targetPort: {{ .Values.service.port.db }}
  selector:
    serviceLabel: {{ .Values.service.label }}

