version: '3.1'
services:
  # MYSQL
  app_db:
    image: mysql:latest
    container_name: app-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: jigu
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db-test
    ports:
      - "3306:3306"
    networks:
      - jigu-network

  jigu_server:
    container_name: jigu-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - app-db
    networks:
      - jigu-network
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: jigu
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db-test

networks:
  jigu-network:
    driver: bridge
